/*
Cisco Intersight

Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document.

API version: 1.0.11-2026011407
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the ApplianceClusterWorkerNodeReplace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplianceClusterWorkerNodeReplace{}

// ApplianceClusterWorkerNodeReplace ClusterWorkerNodeReplace is an object that marks the worker node out of service for replacement.
type ApplianceClusterWorkerNodeReplace struct {
	MoBaseMo
	// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
	ClassId string `json:"ClassId"`
	// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
	ObjectType string `json:"ObjectType"`
	// Hostname of the worker node being replaced.
	Hostname             *string                        `json:"Hostname,omitempty"`
	Account              NullableIamAccountRelationship `json:"Account,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApplianceClusterWorkerNodeReplace ApplianceClusterWorkerNodeReplace

// NewApplianceClusterWorkerNodeReplace instantiates a new ApplianceClusterWorkerNodeReplace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplianceClusterWorkerNodeReplace(classId string, objectType string) *ApplianceClusterWorkerNodeReplace {
	this := ApplianceClusterWorkerNodeReplace{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewApplianceClusterWorkerNodeReplaceWithDefaults instantiates a new ApplianceClusterWorkerNodeReplace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplianceClusterWorkerNodeReplaceWithDefaults() *ApplianceClusterWorkerNodeReplace {
	this := ApplianceClusterWorkerNodeReplace{}
	var classId string = "appliance.ClusterWorkerNodeReplace"
	this.ClassId = classId
	var objectType string = "appliance.ClusterWorkerNodeReplace"
	this.ObjectType = objectType
	return &this
}

// GetClassId returns the ClassId field value
func (o *ApplianceClusterWorkerNodeReplace) GetClassId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *ApplianceClusterWorkerNodeReplace) GetClassIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *ApplianceClusterWorkerNodeReplace) SetClassId(v string) {
	o.ClassId = v
}

// GetDefaultClassId returns the default value "appliance.ClusterWorkerNodeReplace" of the ClassId field.
func (o *ApplianceClusterWorkerNodeReplace) GetDefaultClassId() interface{} {
	return "appliance.ClusterWorkerNodeReplace"
}

// GetObjectType returns the ObjectType field value
func (o *ApplianceClusterWorkerNodeReplace) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *ApplianceClusterWorkerNodeReplace) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *ApplianceClusterWorkerNodeReplace) SetObjectType(v string) {
	o.ObjectType = v
}

// GetDefaultObjectType returns the default value "appliance.ClusterWorkerNodeReplace" of the ObjectType field.
func (o *ApplianceClusterWorkerNodeReplace) GetDefaultObjectType() interface{} {
	return "appliance.ClusterWorkerNodeReplace"
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *ApplianceClusterWorkerNodeReplace) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplianceClusterWorkerNodeReplace) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *ApplianceClusterWorkerNodeReplace) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *ApplianceClusterWorkerNodeReplace) SetHostname(v string) {
	o.Hostname = &v
}

// GetAccount returns the Account field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApplianceClusterWorkerNodeReplace) GetAccount() IamAccountRelationship {
	if o == nil || IsNil(o.Account.Get()) {
		var ret IamAccountRelationship
		return ret
	}
	return *o.Account.Get()
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApplianceClusterWorkerNodeReplace) GetAccountOk() (*IamAccountRelationship, bool) {
	if o == nil {
		return nil, false
	}
	return o.Account.Get(), o.Account.IsSet()
}

// HasAccount returns a boolean if a field has been set.
func (o *ApplianceClusterWorkerNodeReplace) HasAccount() bool {
	if o != nil && o.Account.IsSet() {
		return true
	}

	return false
}

// SetAccount gets a reference to the given NullableIamAccountRelationship and assigns it to the Account field.
func (o *ApplianceClusterWorkerNodeReplace) SetAccount(v IamAccountRelationship) {
	o.Account.Set(&v)
}

// SetAccountNil sets the value for Account to be an explicit nil
func (o *ApplianceClusterWorkerNodeReplace) SetAccountNil() {
	o.Account.Set(nil)
}

// UnsetAccount ensures that no value is present for Account, not even an explicit nil
func (o *ApplianceClusterWorkerNodeReplace) UnsetAccount() {
	o.Account.Unset()
}

func (o ApplianceClusterWorkerNodeReplace) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplianceClusterWorkerNodeReplace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedMoBaseMo, errMoBaseMo := json.Marshal(o.MoBaseMo)
	if errMoBaseMo != nil {
		return map[string]interface{}{}, errMoBaseMo
	}
	errMoBaseMo = json.Unmarshal([]byte(serializedMoBaseMo), &toSerialize)
	if errMoBaseMo != nil {
		return map[string]interface{}{}, errMoBaseMo
	}
	if _, exists := toSerialize["ClassId"]; !exists {
		toSerialize["ClassId"] = o.GetDefaultClassId()
	}
	toSerialize["ClassId"] = o.ClassId
	if _, exists := toSerialize["ObjectType"]; !exists {
		toSerialize["ObjectType"] = o.GetDefaultObjectType()
	}
	toSerialize["ObjectType"] = o.ObjectType
	if !IsNil(o.Hostname) {
		toSerialize["Hostname"] = o.Hostname
	}
	if o.Account.IsSet() {
		toSerialize["Account"] = o.Account.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplianceClusterWorkerNodeReplace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{
		"ClassId":    o.GetDefaultClassId,
		"ObjectType": o.GetDefaultObjectType,
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	type ApplianceClusterWorkerNodeReplaceWithoutEmbeddedStruct struct {
		// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
		ClassId string `json:"ClassId"`
		// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
		ObjectType string `json:"ObjectType"`
		// Hostname of the worker node being replaced.
		Hostname *string                        `json:"Hostname,omitempty"`
		Account  NullableIamAccountRelationship `json:"Account,omitempty"`
	}

	varApplianceClusterWorkerNodeReplaceWithoutEmbeddedStruct := ApplianceClusterWorkerNodeReplaceWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varApplianceClusterWorkerNodeReplaceWithoutEmbeddedStruct)
	if err == nil {
		varApplianceClusterWorkerNodeReplace := _ApplianceClusterWorkerNodeReplace{}
		varApplianceClusterWorkerNodeReplace.ClassId = varApplianceClusterWorkerNodeReplaceWithoutEmbeddedStruct.ClassId
		varApplianceClusterWorkerNodeReplace.ObjectType = varApplianceClusterWorkerNodeReplaceWithoutEmbeddedStruct.ObjectType
		varApplianceClusterWorkerNodeReplace.Hostname = varApplianceClusterWorkerNodeReplaceWithoutEmbeddedStruct.Hostname
		varApplianceClusterWorkerNodeReplace.Account = varApplianceClusterWorkerNodeReplaceWithoutEmbeddedStruct.Account
		*o = ApplianceClusterWorkerNodeReplace(varApplianceClusterWorkerNodeReplace)
	} else {
		return err
	}

	varApplianceClusterWorkerNodeReplace := _ApplianceClusterWorkerNodeReplace{}

	err = json.Unmarshal(data, &varApplianceClusterWorkerNodeReplace)
	if err == nil {
		o.MoBaseMo = varApplianceClusterWorkerNodeReplace.MoBaseMo
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ClassId")
		delete(additionalProperties, "ObjectType")
		delete(additionalProperties, "Hostname")
		delete(additionalProperties, "Account")

		// remove fields from embedded structs
		reflectMoBaseMo := reflect.ValueOf(o.MoBaseMo)
		for i := 0; i < reflectMoBaseMo.Type().NumField(); i++ {
			t := reflectMoBaseMo.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplianceClusterWorkerNodeReplace struct {
	value *ApplianceClusterWorkerNodeReplace
	isSet bool
}

func (v NullableApplianceClusterWorkerNodeReplace) Get() *ApplianceClusterWorkerNodeReplace {
	return v.value
}

func (v *NullableApplianceClusterWorkerNodeReplace) Set(val *ApplianceClusterWorkerNodeReplace) {
	v.value = val
	v.isSet = true
}

func (v NullableApplianceClusterWorkerNodeReplace) IsSet() bool {
	return v.isSet
}

func (v *NullableApplianceClusterWorkerNodeReplace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplianceClusterWorkerNodeReplace(val *ApplianceClusterWorkerNodeReplace) *NullableApplianceClusterWorkerNodeReplace {
	return &NullableApplianceClusterWorkerNodeReplace{value: val, isSet: true}
}

func (v NullableApplianceClusterWorkerNodeReplace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplianceClusterWorkerNodeReplace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
