/*
Cisco Intersight

Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document.

API version: 1.0.11-13892
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
)

// VirtualizationBaseHostPciDeviceAllOf Definition of the list of properties defined in 'virtualization.BaseHostPciDevice', excluding properties defined in parent classes.
type VirtualizationBaseHostPciDeviceAllOf struct {
	// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data. The enum values provides the list of concrete types that can be instantiated from this abstract type.
	ClassId string `json:"ClassId"`
	// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property. The enum values provides the list of concrete types that can be instantiated from this abstract type.
	ObjectType string `json:"ObjectType"`
	// The bus ID of this PCI device.
	Bus *int64 `json:"Bus,omitempty"`
	// The device ID of this PCI device.
	DeviceId *int64 `json:"DeviceId,omitempty"`
	// The device name of this PCI device.
	DeviceName *string `json:"DeviceName,omitempty"`
	// The function ID of this PCI device.
	Function *int64 `json:"Function,omitempty"`
	// The internally generated identity of this PCI device.
	Identity *string `json:"Identity,omitempty"`
	// Indicates if passthrough is active for this PCI device (meaning enabled + rebooted).
	PassthroughActive *bool `json:"PassthroughActive,omitempty"`
	// Indicates if passthrough feature is enabled for this PCI device. PCI passthrough feature enables you to access and manage hardware devices from a virtual machine. When PCI passthrough is configured, the PCI devices function as if they were physically attached to the guest operating system.
	PassthroughEnabled *bool `json:"PassthroughEnabled,omitempty"`
	// The class ID of this PCI device.
	PciClassId *int64 `json:"PciClassId,omitempty"`
	// The ID of this PCI device.
	PciId *string `json:"PciId,omitempty"`
	// The slot ID of this PCI device.
	Slot *int64 `json:"Slot,omitempty"`
	// The sub device ID of this PCI device.
	SubDeviceId *int64 `json:"SubDeviceId,omitempty"`
	// The sub vendor ID of this PCI device.
	SubVendorId *int64 `json:"SubVendorId,omitempty"`
	// The vendor ID of this PCI device.
	VendorId *int64 `json:"VendorId,omitempty"`
	// The vendor name of this PCI device.
	VendorName           *string                                `json:"VendorName,omitempty"`
	Cluster              *VirtualizationBaseClusterRelationship `json:"Cluster,omitempty"`
	Host                 *VirtualizationBaseHostRelationship    `json:"Host,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VirtualizationBaseHostPciDeviceAllOf VirtualizationBaseHostPciDeviceAllOf

// NewVirtualizationBaseHostPciDeviceAllOf instantiates a new VirtualizationBaseHostPciDeviceAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualizationBaseHostPciDeviceAllOf(classId string, objectType string) *VirtualizationBaseHostPciDeviceAllOf {
	this := VirtualizationBaseHostPciDeviceAllOf{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewVirtualizationBaseHostPciDeviceAllOfWithDefaults instantiates a new VirtualizationBaseHostPciDeviceAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualizationBaseHostPciDeviceAllOfWithDefaults() *VirtualizationBaseHostPciDeviceAllOf {
	this := VirtualizationBaseHostPciDeviceAllOf{}
	var classId string = "virtualization.VmwareHostGpu"
	this.ClassId = classId
	var objectType string = "virtualization.VmwareHostGpu"
	this.ObjectType = objectType
	return &this
}

// GetClassId returns the ClassId field value
func (o *VirtualizationBaseHostPciDeviceAllOf) GetClassId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetClassIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *VirtualizationBaseHostPciDeviceAllOf) SetClassId(v string) {
	o.ClassId = v
}

// GetObjectType returns the ObjectType field value
func (o *VirtualizationBaseHostPciDeviceAllOf) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *VirtualizationBaseHostPciDeviceAllOf) SetObjectType(v string) {
	o.ObjectType = v
}

// GetBus returns the Bus field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetBus() int64 {
	if o == nil || o.Bus == nil {
		var ret int64
		return ret
	}
	return *o.Bus
}

// GetBusOk returns a tuple with the Bus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetBusOk() (*int64, bool) {
	if o == nil || o.Bus == nil {
		return nil, false
	}
	return o.Bus, true
}

// HasBus returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasBus() bool {
	if o != nil && o.Bus != nil {
		return true
	}

	return false
}

// SetBus gets a reference to the given int64 and assigns it to the Bus field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetBus(v int64) {
	o.Bus = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetDeviceId() int64 {
	if o == nil || o.DeviceId == nil {
		var ret int64
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetDeviceIdOk() (*int64, bool) {
	if o == nil || o.DeviceId == nil {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasDeviceId() bool {
	if o != nil && o.DeviceId != nil {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given int64 and assigns it to the DeviceId field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetDeviceId(v int64) {
	o.DeviceId = &v
}

// GetDeviceName returns the DeviceName field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetDeviceName() string {
	if o == nil || o.DeviceName == nil {
		var ret string
		return ret
	}
	return *o.DeviceName
}

// GetDeviceNameOk returns a tuple with the DeviceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetDeviceNameOk() (*string, bool) {
	if o == nil || o.DeviceName == nil {
		return nil, false
	}
	return o.DeviceName, true
}

// HasDeviceName returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasDeviceName() bool {
	if o != nil && o.DeviceName != nil {
		return true
	}

	return false
}

// SetDeviceName gets a reference to the given string and assigns it to the DeviceName field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetDeviceName(v string) {
	o.DeviceName = &v
}

// GetFunction returns the Function field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetFunction() int64 {
	if o == nil || o.Function == nil {
		var ret int64
		return ret
	}
	return *o.Function
}

// GetFunctionOk returns a tuple with the Function field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetFunctionOk() (*int64, bool) {
	if o == nil || o.Function == nil {
		return nil, false
	}
	return o.Function, true
}

// HasFunction returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasFunction() bool {
	if o != nil && o.Function != nil {
		return true
	}

	return false
}

// SetFunction gets a reference to the given int64 and assigns it to the Function field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetFunction(v int64) {
	o.Function = &v
}

// GetIdentity returns the Identity field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetIdentity() string {
	if o == nil || o.Identity == nil {
		var ret string
		return ret
	}
	return *o.Identity
}

// GetIdentityOk returns a tuple with the Identity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetIdentityOk() (*string, bool) {
	if o == nil || o.Identity == nil {
		return nil, false
	}
	return o.Identity, true
}

// HasIdentity returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasIdentity() bool {
	if o != nil && o.Identity != nil {
		return true
	}

	return false
}

// SetIdentity gets a reference to the given string and assigns it to the Identity field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetIdentity(v string) {
	o.Identity = &v
}

// GetPassthroughActive returns the PassthroughActive field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetPassthroughActive() bool {
	if o == nil || o.PassthroughActive == nil {
		var ret bool
		return ret
	}
	return *o.PassthroughActive
}

// GetPassthroughActiveOk returns a tuple with the PassthroughActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetPassthroughActiveOk() (*bool, bool) {
	if o == nil || o.PassthroughActive == nil {
		return nil, false
	}
	return o.PassthroughActive, true
}

// HasPassthroughActive returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasPassthroughActive() bool {
	if o != nil && o.PassthroughActive != nil {
		return true
	}

	return false
}

// SetPassthroughActive gets a reference to the given bool and assigns it to the PassthroughActive field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetPassthroughActive(v bool) {
	o.PassthroughActive = &v
}

// GetPassthroughEnabled returns the PassthroughEnabled field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetPassthroughEnabled() bool {
	if o == nil || o.PassthroughEnabled == nil {
		var ret bool
		return ret
	}
	return *o.PassthroughEnabled
}

// GetPassthroughEnabledOk returns a tuple with the PassthroughEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetPassthroughEnabledOk() (*bool, bool) {
	if o == nil || o.PassthroughEnabled == nil {
		return nil, false
	}
	return o.PassthroughEnabled, true
}

// HasPassthroughEnabled returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasPassthroughEnabled() bool {
	if o != nil && o.PassthroughEnabled != nil {
		return true
	}

	return false
}

// SetPassthroughEnabled gets a reference to the given bool and assigns it to the PassthroughEnabled field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetPassthroughEnabled(v bool) {
	o.PassthroughEnabled = &v
}

// GetPciClassId returns the PciClassId field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetPciClassId() int64 {
	if o == nil || o.PciClassId == nil {
		var ret int64
		return ret
	}
	return *o.PciClassId
}

// GetPciClassIdOk returns a tuple with the PciClassId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetPciClassIdOk() (*int64, bool) {
	if o == nil || o.PciClassId == nil {
		return nil, false
	}
	return o.PciClassId, true
}

// HasPciClassId returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasPciClassId() bool {
	if o != nil && o.PciClassId != nil {
		return true
	}

	return false
}

// SetPciClassId gets a reference to the given int64 and assigns it to the PciClassId field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetPciClassId(v int64) {
	o.PciClassId = &v
}

// GetPciId returns the PciId field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetPciId() string {
	if o == nil || o.PciId == nil {
		var ret string
		return ret
	}
	return *o.PciId
}

// GetPciIdOk returns a tuple with the PciId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetPciIdOk() (*string, bool) {
	if o == nil || o.PciId == nil {
		return nil, false
	}
	return o.PciId, true
}

// HasPciId returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasPciId() bool {
	if o != nil && o.PciId != nil {
		return true
	}

	return false
}

// SetPciId gets a reference to the given string and assigns it to the PciId field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetPciId(v string) {
	o.PciId = &v
}

// GetSlot returns the Slot field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetSlot() int64 {
	if o == nil || o.Slot == nil {
		var ret int64
		return ret
	}
	return *o.Slot
}

// GetSlotOk returns a tuple with the Slot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetSlotOk() (*int64, bool) {
	if o == nil || o.Slot == nil {
		return nil, false
	}
	return o.Slot, true
}

// HasSlot returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasSlot() bool {
	if o != nil && o.Slot != nil {
		return true
	}

	return false
}

// SetSlot gets a reference to the given int64 and assigns it to the Slot field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetSlot(v int64) {
	o.Slot = &v
}

// GetSubDeviceId returns the SubDeviceId field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetSubDeviceId() int64 {
	if o == nil || o.SubDeviceId == nil {
		var ret int64
		return ret
	}
	return *o.SubDeviceId
}

// GetSubDeviceIdOk returns a tuple with the SubDeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetSubDeviceIdOk() (*int64, bool) {
	if o == nil || o.SubDeviceId == nil {
		return nil, false
	}
	return o.SubDeviceId, true
}

// HasSubDeviceId returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasSubDeviceId() bool {
	if o != nil && o.SubDeviceId != nil {
		return true
	}

	return false
}

// SetSubDeviceId gets a reference to the given int64 and assigns it to the SubDeviceId field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetSubDeviceId(v int64) {
	o.SubDeviceId = &v
}

// GetSubVendorId returns the SubVendorId field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetSubVendorId() int64 {
	if o == nil || o.SubVendorId == nil {
		var ret int64
		return ret
	}
	return *o.SubVendorId
}

// GetSubVendorIdOk returns a tuple with the SubVendorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetSubVendorIdOk() (*int64, bool) {
	if o == nil || o.SubVendorId == nil {
		return nil, false
	}
	return o.SubVendorId, true
}

// HasSubVendorId returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasSubVendorId() bool {
	if o != nil && o.SubVendorId != nil {
		return true
	}

	return false
}

// SetSubVendorId gets a reference to the given int64 and assigns it to the SubVendorId field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetSubVendorId(v int64) {
	o.SubVendorId = &v
}

// GetVendorId returns the VendorId field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetVendorId() int64 {
	if o == nil || o.VendorId == nil {
		var ret int64
		return ret
	}
	return *o.VendorId
}

// GetVendorIdOk returns a tuple with the VendorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetVendorIdOk() (*int64, bool) {
	if o == nil || o.VendorId == nil {
		return nil, false
	}
	return o.VendorId, true
}

// HasVendorId returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasVendorId() bool {
	if o != nil && o.VendorId != nil {
		return true
	}

	return false
}

// SetVendorId gets a reference to the given int64 and assigns it to the VendorId field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetVendorId(v int64) {
	o.VendorId = &v
}

// GetVendorName returns the VendorName field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetVendorName() string {
	if o == nil || o.VendorName == nil {
		var ret string
		return ret
	}
	return *o.VendorName
}

// GetVendorNameOk returns a tuple with the VendorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetVendorNameOk() (*string, bool) {
	if o == nil || o.VendorName == nil {
		return nil, false
	}
	return o.VendorName, true
}

// HasVendorName returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasVendorName() bool {
	if o != nil && o.VendorName != nil {
		return true
	}

	return false
}

// SetVendorName gets a reference to the given string and assigns it to the VendorName field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetVendorName(v string) {
	o.VendorName = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetCluster() VirtualizationBaseClusterRelationship {
	if o == nil || o.Cluster == nil {
		var ret VirtualizationBaseClusterRelationship
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetClusterOk() (*VirtualizationBaseClusterRelationship, bool) {
	if o == nil || o.Cluster == nil {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasCluster() bool {
	if o != nil && o.Cluster != nil {
		return true
	}

	return false
}

// SetCluster gets a reference to the given VirtualizationBaseClusterRelationship and assigns it to the Cluster field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetCluster(v VirtualizationBaseClusterRelationship) {
	o.Cluster = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetHost() VirtualizationBaseHostRelationship {
	if o == nil || o.Host == nil {
		var ret VirtualizationBaseHostRelationship
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) GetHostOk() (*VirtualizationBaseHostRelationship, bool) {
	if o == nil || o.Host == nil {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *VirtualizationBaseHostPciDeviceAllOf) HasHost() bool {
	if o != nil && o.Host != nil {
		return true
	}

	return false
}

// SetHost gets a reference to the given VirtualizationBaseHostRelationship and assigns it to the Host field.
func (o *VirtualizationBaseHostPciDeviceAllOf) SetHost(v VirtualizationBaseHostRelationship) {
	o.Host = &v
}

func (o VirtualizationBaseHostPciDeviceAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ClassId"] = o.ClassId
	}
	if true {
		toSerialize["ObjectType"] = o.ObjectType
	}
	if o.Bus != nil {
		toSerialize["Bus"] = o.Bus
	}
	if o.DeviceId != nil {
		toSerialize["DeviceId"] = o.DeviceId
	}
	if o.DeviceName != nil {
		toSerialize["DeviceName"] = o.DeviceName
	}
	if o.Function != nil {
		toSerialize["Function"] = o.Function
	}
	if o.Identity != nil {
		toSerialize["Identity"] = o.Identity
	}
	if o.PassthroughActive != nil {
		toSerialize["PassthroughActive"] = o.PassthroughActive
	}
	if o.PassthroughEnabled != nil {
		toSerialize["PassthroughEnabled"] = o.PassthroughEnabled
	}
	if o.PciClassId != nil {
		toSerialize["PciClassId"] = o.PciClassId
	}
	if o.PciId != nil {
		toSerialize["PciId"] = o.PciId
	}
	if o.Slot != nil {
		toSerialize["Slot"] = o.Slot
	}
	if o.SubDeviceId != nil {
		toSerialize["SubDeviceId"] = o.SubDeviceId
	}
	if o.SubVendorId != nil {
		toSerialize["SubVendorId"] = o.SubVendorId
	}
	if o.VendorId != nil {
		toSerialize["VendorId"] = o.VendorId
	}
	if o.VendorName != nil {
		toSerialize["VendorName"] = o.VendorName
	}
	if o.Cluster != nil {
		toSerialize["Cluster"] = o.Cluster
	}
	if o.Host != nil {
		toSerialize["Host"] = o.Host
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *VirtualizationBaseHostPciDeviceAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varVirtualizationBaseHostPciDeviceAllOf := _VirtualizationBaseHostPciDeviceAllOf{}

	if err = json.Unmarshal(bytes, &varVirtualizationBaseHostPciDeviceAllOf); err == nil {
		*o = VirtualizationBaseHostPciDeviceAllOf(varVirtualizationBaseHostPciDeviceAllOf)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "ClassId")
		delete(additionalProperties, "ObjectType")
		delete(additionalProperties, "Bus")
		delete(additionalProperties, "DeviceId")
		delete(additionalProperties, "DeviceName")
		delete(additionalProperties, "Function")
		delete(additionalProperties, "Identity")
		delete(additionalProperties, "PassthroughActive")
		delete(additionalProperties, "PassthroughEnabled")
		delete(additionalProperties, "PciClassId")
		delete(additionalProperties, "PciId")
		delete(additionalProperties, "Slot")
		delete(additionalProperties, "SubDeviceId")
		delete(additionalProperties, "SubVendorId")
		delete(additionalProperties, "VendorId")
		delete(additionalProperties, "VendorName")
		delete(additionalProperties, "Cluster")
		delete(additionalProperties, "Host")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVirtualizationBaseHostPciDeviceAllOf struct {
	value *VirtualizationBaseHostPciDeviceAllOf
	isSet bool
}

func (v NullableVirtualizationBaseHostPciDeviceAllOf) Get() *VirtualizationBaseHostPciDeviceAllOf {
	return v.value
}

func (v *NullableVirtualizationBaseHostPciDeviceAllOf) Set(val *VirtualizationBaseHostPciDeviceAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualizationBaseHostPciDeviceAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualizationBaseHostPciDeviceAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualizationBaseHostPciDeviceAllOf(val *VirtualizationBaseHostPciDeviceAllOf) *NullableVirtualizationBaseHostPciDeviceAllOf {
	return &NullableVirtualizationBaseHostPciDeviceAllOf{value: val, isSet: true}
}

func (v NullableVirtualizationBaseHostPciDeviceAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualizationBaseHostPciDeviceAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
