/*
Cisco Intersight

Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document.

API version: 1.0.11-2026041816
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the WorkloadRenameRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkloadRenameRequest{}

// WorkloadRenameRequest The request for a rename operation on an object.
type WorkloadRenameRequest struct {
	MoBaseComplexType
	// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
	ClassId string `json:"ClassId"`
	// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
	ObjectType string `json:"ObjectType"`
	// The action to be taken for the rename operation on an object. * `None` - No action is to be taken for the rename request. * `Rename` - The object is to be renamed with the new name in the request.
	Action *string `json:"Action,omitempty"`
	// The new name for the object. This name will be used to rename all objects associated with it.
	NewName *string `json:"NewName,omitempty"`
	// The status of the rename operation for an object. * `None` - No rename operation is in progress, the last rename operation succeeded, or rename has not been performed on the object. * `Updating` - The object is currently being renamed. * `UpdateScheduled` - The rename request for the object has been accepted and will be processed.
	Status               *string `json:"Status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WorkloadRenameRequest WorkloadRenameRequest

// NewWorkloadRenameRequest instantiates a new WorkloadRenameRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkloadRenameRequest(classId string, objectType string) *WorkloadRenameRequest {
	this := WorkloadRenameRequest{}
	this.ClassId = classId
	this.ObjectType = objectType
	var action string = "None"
	this.Action = &action
	return &this
}

// NewWorkloadRenameRequestWithDefaults instantiates a new WorkloadRenameRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkloadRenameRequestWithDefaults() *WorkloadRenameRequest {
	this := WorkloadRenameRequest{}
	var classId string = "workload.RenameRequest"
	this.ClassId = classId
	var objectType string = "workload.RenameRequest"
	this.ObjectType = objectType
	var action string = "None"
	this.Action = &action
	return &this
}

// GetClassId returns the ClassId field value
func (o *WorkloadRenameRequest) GetClassId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *WorkloadRenameRequest) GetClassIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *WorkloadRenameRequest) SetClassId(v string) {
	o.ClassId = v
}

// GetDefaultClassId returns the default value "workload.RenameRequest" of the ClassId field.
func (o *WorkloadRenameRequest) GetDefaultClassId() interface{} {
	return "workload.RenameRequest"
}

// GetObjectType returns the ObjectType field value
func (o *WorkloadRenameRequest) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *WorkloadRenameRequest) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *WorkloadRenameRequest) SetObjectType(v string) {
	o.ObjectType = v
}

// GetDefaultObjectType returns the default value "workload.RenameRequest" of the ObjectType field.
func (o *WorkloadRenameRequest) GetDefaultObjectType() interface{} {
	return "workload.RenameRequest"
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *WorkloadRenameRequest) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRenameRequest) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *WorkloadRenameRequest) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *WorkloadRenameRequest) SetAction(v string) {
	o.Action = &v
}

// GetNewName returns the NewName field value if set, zero value otherwise.
func (o *WorkloadRenameRequest) GetNewName() string {
	if o == nil || IsNil(o.NewName) {
		var ret string
		return ret
	}
	return *o.NewName
}

// GetNewNameOk returns a tuple with the NewName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRenameRequest) GetNewNameOk() (*string, bool) {
	if o == nil || IsNil(o.NewName) {
		return nil, false
	}
	return o.NewName, true
}

// HasNewName returns a boolean if a field has been set.
func (o *WorkloadRenameRequest) HasNewName() bool {
	if o != nil && !IsNil(o.NewName) {
		return true
	}

	return false
}

// SetNewName gets a reference to the given string and assigns it to the NewName field.
func (o *WorkloadRenameRequest) SetNewName(v string) {
	o.NewName = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WorkloadRenameRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadRenameRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WorkloadRenameRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *WorkloadRenameRequest) SetStatus(v string) {
	o.Status = &v
}

func (o WorkloadRenameRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkloadRenameRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedMoBaseComplexType, errMoBaseComplexType := json.Marshal(o.MoBaseComplexType)
	if errMoBaseComplexType != nil {
		return map[string]interface{}{}, errMoBaseComplexType
	}
	errMoBaseComplexType = json.Unmarshal([]byte(serializedMoBaseComplexType), &toSerialize)
	if errMoBaseComplexType != nil {
		return map[string]interface{}{}, errMoBaseComplexType
	}
	if _, exists := toSerialize["ClassId"]; !exists {
		toSerialize["ClassId"] = o.GetDefaultClassId()
	}
	toSerialize["ClassId"] = o.ClassId
	if _, exists := toSerialize["ObjectType"]; !exists {
		toSerialize["ObjectType"] = o.GetDefaultObjectType()
	}
	toSerialize["ObjectType"] = o.ObjectType
	if !IsNil(o.Action) {
		toSerialize["Action"] = o.Action
	}
	if !IsNil(o.NewName) {
		toSerialize["NewName"] = o.NewName
	}
	if !IsNil(o.Status) {
		toSerialize["Status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkloadRenameRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{
		"ClassId":    o.GetDefaultClassId,
		"ObjectType": o.GetDefaultObjectType,
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	type WorkloadRenameRequestWithoutEmbeddedStruct struct {
		// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
		ClassId string `json:"ClassId"`
		// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
		ObjectType string `json:"ObjectType"`
		// The action to be taken for the rename operation on an object. * `None` - No action is to be taken for the rename request. * `Rename` - The object is to be renamed with the new name in the request.
		Action *string `json:"Action,omitempty"`
		// The new name for the object. This name will be used to rename all objects associated with it.
		NewName *string `json:"NewName,omitempty"`
		// The status of the rename operation for an object. * `None` - No rename operation is in progress, the last rename operation succeeded, or rename has not been performed on the object. * `Updating` - The object is currently being renamed. * `UpdateScheduled` - The rename request for the object has been accepted and will be processed.
		Status *string `json:"Status,omitempty"`
	}

	varWorkloadRenameRequestWithoutEmbeddedStruct := WorkloadRenameRequestWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varWorkloadRenameRequestWithoutEmbeddedStruct)
	if err == nil {
		varWorkloadRenameRequest := _WorkloadRenameRequest{}
		varWorkloadRenameRequest.ClassId = varWorkloadRenameRequestWithoutEmbeddedStruct.ClassId
		varWorkloadRenameRequest.ObjectType = varWorkloadRenameRequestWithoutEmbeddedStruct.ObjectType
		varWorkloadRenameRequest.Action = varWorkloadRenameRequestWithoutEmbeddedStruct.Action
		varWorkloadRenameRequest.NewName = varWorkloadRenameRequestWithoutEmbeddedStruct.NewName
		varWorkloadRenameRequest.Status = varWorkloadRenameRequestWithoutEmbeddedStruct.Status
		*o = WorkloadRenameRequest(varWorkloadRenameRequest)
	} else {
		return err
	}

	varWorkloadRenameRequest := _WorkloadRenameRequest{}

	err = json.Unmarshal(data, &varWorkloadRenameRequest)
	if err == nil {
		o.MoBaseComplexType = varWorkloadRenameRequest.MoBaseComplexType
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ClassId")
		delete(additionalProperties, "ObjectType")
		delete(additionalProperties, "Action")
		delete(additionalProperties, "NewName")
		delete(additionalProperties, "Status")

		// remove fields from embedded structs
		reflectMoBaseComplexType := reflect.ValueOf(o.MoBaseComplexType)
		for i := 0; i < reflectMoBaseComplexType.Type().NumField(); i++ {
			t := reflectMoBaseComplexType.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkloadRenameRequest struct {
	value *WorkloadRenameRequest
	isSet bool
}

func (v NullableWorkloadRenameRequest) Get() *WorkloadRenameRequest {
	return v.value
}

func (v *NullableWorkloadRenameRequest) Set(val *WorkloadRenameRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkloadRenameRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkloadRenameRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkloadRenameRequest(val *WorkloadRenameRequest) *NullableWorkloadRenameRequest {
	return &NullableWorkloadRenameRequest{value: val, isSet: true}
}

func (v NullableWorkloadRenameRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkloadRenameRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
