/*
Cisco Intersight

Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document.

API version: 1.0.11-13010
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
)

// ServiceitemSelectionCriteriaInputAllOf Definition of the list of properties defined in 'serviceitem.SelectionCriteriaInput', excluding properties defined in parent classes.
type ServiceitemSelectionCriteriaInputAllOf struct {
	// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
	ClassId string `json:"ClassId"`
	// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
	ObjectType       string             `json:"ObjectType"`
	FilterConditions []ResourceSelector `json:"FilterConditions,omitempty"`
	// Name of the Policy Input.
	InputName *string `json:"InputName,omitempty"`
	// The value extracted from the filter conditions.
	InputValue           interface{} `json:"InputValue,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceitemSelectionCriteriaInputAllOf ServiceitemSelectionCriteriaInputAllOf

// NewServiceitemSelectionCriteriaInputAllOf instantiates a new ServiceitemSelectionCriteriaInputAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceitemSelectionCriteriaInputAllOf(classId string, objectType string) *ServiceitemSelectionCriteriaInputAllOf {
	this := ServiceitemSelectionCriteriaInputAllOf{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewServiceitemSelectionCriteriaInputAllOfWithDefaults instantiates a new ServiceitemSelectionCriteriaInputAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceitemSelectionCriteriaInputAllOfWithDefaults() *ServiceitemSelectionCriteriaInputAllOf {
	this := ServiceitemSelectionCriteriaInputAllOf{}
	var classId string = "serviceitem.SelectionCriteriaInput"
	this.ClassId = classId
	var objectType string = "serviceitem.SelectionCriteriaInput"
	this.ObjectType = objectType
	return &this
}

// GetClassId returns the ClassId field value
func (o *ServiceitemSelectionCriteriaInputAllOf) GetClassId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *ServiceitemSelectionCriteriaInputAllOf) GetClassIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *ServiceitemSelectionCriteriaInputAllOf) SetClassId(v string) {
	o.ClassId = v
}

// GetObjectType returns the ObjectType field value
func (o *ServiceitemSelectionCriteriaInputAllOf) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *ServiceitemSelectionCriteriaInputAllOf) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *ServiceitemSelectionCriteriaInputAllOf) SetObjectType(v string) {
	o.ObjectType = v
}

// GetFilterConditions returns the FilterConditions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceitemSelectionCriteriaInputAllOf) GetFilterConditions() []ResourceSelector {
	if o == nil {
		var ret []ResourceSelector
		return ret
	}
	return o.FilterConditions
}

// GetFilterConditionsOk returns a tuple with the FilterConditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceitemSelectionCriteriaInputAllOf) GetFilterConditionsOk() ([]ResourceSelector, bool) {
	if o == nil || o.FilterConditions == nil {
		return nil, false
	}
	return o.FilterConditions, true
}

// HasFilterConditions returns a boolean if a field has been set.
func (o *ServiceitemSelectionCriteriaInputAllOf) HasFilterConditions() bool {
	if o != nil && o.FilterConditions != nil {
		return true
	}

	return false
}

// SetFilterConditions gets a reference to the given []ResourceSelector and assigns it to the FilterConditions field.
func (o *ServiceitemSelectionCriteriaInputAllOf) SetFilterConditions(v []ResourceSelector) {
	o.FilterConditions = v
}

// GetInputName returns the InputName field value if set, zero value otherwise.
func (o *ServiceitemSelectionCriteriaInputAllOf) GetInputName() string {
	if o == nil || o.InputName == nil {
		var ret string
		return ret
	}
	return *o.InputName
}

// GetInputNameOk returns a tuple with the InputName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceitemSelectionCriteriaInputAllOf) GetInputNameOk() (*string, bool) {
	if o == nil || o.InputName == nil {
		return nil, false
	}
	return o.InputName, true
}

// HasInputName returns a boolean if a field has been set.
func (o *ServiceitemSelectionCriteriaInputAllOf) HasInputName() bool {
	if o != nil && o.InputName != nil {
		return true
	}

	return false
}

// SetInputName gets a reference to the given string and assigns it to the InputName field.
func (o *ServiceitemSelectionCriteriaInputAllOf) SetInputName(v string) {
	o.InputName = &v
}

// GetInputValue returns the InputValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceitemSelectionCriteriaInputAllOf) GetInputValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InputValue
}

// GetInputValueOk returns a tuple with the InputValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceitemSelectionCriteriaInputAllOf) GetInputValueOk() (*interface{}, bool) {
	if o == nil || o.InputValue == nil {
		return nil, false
	}
	return &o.InputValue, true
}

// HasInputValue returns a boolean if a field has been set.
func (o *ServiceitemSelectionCriteriaInputAllOf) HasInputValue() bool {
	if o != nil && o.InputValue != nil {
		return true
	}

	return false
}

// SetInputValue gets a reference to the given interface{} and assigns it to the InputValue field.
func (o *ServiceitemSelectionCriteriaInputAllOf) SetInputValue(v interface{}) {
	o.InputValue = v
}

func (o ServiceitemSelectionCriteriaInputAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ClassId"] = o.ClassId
	}
	if true {
		toSerialize["ObjectType"] = o.ObjectType
	}
	if o.FilterConditions != nil {
		toSerialize["FilterConditions"] = o.FilterConditions
	}
	if o.InputName != nil {
		toSerialize["InputName"] = o.InputName
	}
	if o.InputValue != nil {
		toSerialize["InputValue"] = o.InputValue
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ServiceitemSelectionCriteriaInputAllOf) UnmarshalJSON(bytes []byte) (err error) {
	varServiceitemSelectionCriteriaInputAllOf := _ServiceitemSelectionCriteriaInputAllOf{}

	if err = json.Unmarshal(bytes, &varServiceitemSelectionCriteriaInputAllOf); err == nil {
		*o = ServiceitemSelectionCriteriaInputAllOf(varServiceitemSelectionCriteriaInputAllOf)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "ClassId")
		delete(additionalProperties, "ObjectType")
		delete(additionalProperties, "FilterConditions")
		delete(additionalProperties, "InputName")
		delete(additionalProperties, "InputValue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceitemSelectionCriteriaInputAllOf struct {
	value *ServiceitemSelectionCriteriaInputAllOf
	isSet bool
}

func (v NullableServiceitemSelectionCriteriaInputAllOf) Get() *ServiceitemSelectionCriteriaInputAllOf {
	return v.value
}

func (v *NullableServiceitemSelectionCriteriaInputAllOf) Set(val *ServiceitemSelectionCriteriaInputAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceitemSelectionCriteriaInputAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceitemSelectionCriteriaInputAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceitemSelectionCriteriaInputAllOf(val *ServiceitemSelectionCriteriaInputAllOf) *NullableServiceitemSelectionCriteriaInputAllOf {
	return &NullableServiceitemSelectionCriteriaInputAllOf{value: val, isSet: true}
}

func (v NullableServiceitemSelectionCriteriaInputAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceitemSelectionCriteriaInputAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
