/*
Cisco Intersight

Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document.

API version: 1.0.11-2026011407
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// checks if the WorkloadDeploymentInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkloadDeploymentInput{}

// WorkloadDeploymentInput ### Overview The DeploymentInput object captures a versioned snapshot of all input parameters and configuration values for a workload deployment at a specific point in time. It maintains a complete history of how deployment inputs have evolved, enabling traceability and potential rollback scenarios. #### Purpose DeploymentInput serves as an immutable historical record of deployment configuration states. Each time deployment inputs change, a new DeploymentInput object is created with an incremented generation number. This enables the system to track which workload instances were created with which input configurations and to understand the impact of input changes over time. #### Key Concepts - **Generation-Based Versioning:** - Each input change creates a new generation with an incremented sequence number, providing a complete audit trail of configuration changes. - **Input Composition:** - Combines user-provided inputs at both the workload definition and deployment levels, with deployment-level inputs overriding definition-level inputs where applicable. - **Blueprint Integration:** - Resolves all blueprint-specific inputs and merges them into a unified input structure that can be applied to workload instance creation. - **Object Generation State:** - Tracks whether managed objects (policies, profiles) were successfully generated from this input configuration, supporting rollback scenarios when object generation fails.
type WorkloadDeploymentInput struct {
	MoBaseMo
	// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
	ClassId string `json:"ClassId"`
	// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
	ObjectType string `json:"ObjectType"`
	// A sequential number that increments whenever the input changes.
	GenNumber *int64                                 `json:"GenNumber,omitempty"`
	Input     []WorkloadDeploymentBlueprintInputType `json:"Input,omitempty"`
	// The state of the object generation performed using this input. If object generation fails, then this is set to true when the generated objects are restored to their prior state.
	ObjectGenerationFailed *bool                                          `json:"ObjectGenerationFailed,omitempty"`
	WorkloadDeployment     NullableWorkloadWorkloadDeploymentRelationship `json:"WorkloadDeployment,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _WorkloadDeploymentInput WorkloadDeploymentInput

// NewWorkloadDeploymentInput instantiates a new WorkloadDeploymentInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkloadDeploymentInput(classId string, objectType string) *WorkloadDeploymentInput {
	this := WorkloadDeploymentInput{}
	this.ClassId = classId
	this.ObjectType = objectType
	return &this
}

// NewWorkloadDeploymentInputWithDefaults instantiates a new WorkloadDeploymentInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkloadDeploymentInputWithDefaults() *WorkloadDeploymentInput {
	this := WorkloadDeploymentInput{}
	var classId string = "workload.DeploymentInput"
	this.ClassId = classId
	var objectType string = "workload.DeploymentInput"
	this.ObjectType = objectType
	return &this
}

// GetClassId returns the ClassId field value
func (o *WorkloadDeploymentInput) GetClassId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *WorkloadDeploymentInput) GetClassIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *WorkloadDeploymentInput) SetClassId(v string) {
	o.ClassId = v
}

// GetDefaultClassId returns the default value "workload.DeploymentInput" of the ClassId field.
func (o *WorkloadDeploymentInput) GetDefaultClassId() interface{} {
	return "workload.DeploymentInput"
}

// GetObjectType returns the ObjectType field value
func (o *WorkloadDeploymentInput) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *WorkloadDeploymentInput) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *WorkloadDeploymentInput) SetObjectType(v string) {
	o.ObjectType = v
}

// GetDefaultObjectType returns the default value "workload.DeploymentInput" of the ObjectType field.
func (o *WorkloadDeploymentInput) GetDefaultObjectType() interface{} {
	return "workload.DeploymentInput"
}

// GetGenNumber returns the GenNumber field value if set, zero value otherwise.
func (o *WorkloadDeploymentInput) GetGenNumber() int64 {
	if o == nil || IsNil(o.GenNumber) {
		var ret int64
		return ret
	}
	return *o.GenNumber
}

// GetGenNumberOk returns a tuple with the GenNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadDeploymentInput) GetGenNumberOk() (*int64, bool) {
	if o == nil || IsNil(o.GenNumber) {
		return nil, false
	}
	return o.GenNumber, true
}

// HasGenNumber returns a boolean if a field has been set.
func (o *WorkloadDeploymentInput) HasGenNumber() bool {
	if o != nil && !IsNil(o.GenNumber) {
		return true
	}

	return false
}

// SetGenNumber gets a reference to the given int64 and assigns it to the GenNumber field.
func (o *WorkloadDeploymentInput) SetGenNumber(v int64) {
	o.GenNumber = &v
}

// GetInput returns the Input field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkloadDeploymentInput) GetInput() []WorkloadDeploymentBlueprintInputType {
	if o == nil {
		var ret []WorkloadDeploymentBlueprintInputType
		return ret
	}
	return o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkloadDeploymentInput) GetInputOk() ([]WorkloadDeploymentBlueprintInputType, bool) {
	if o == nil || IsNil(o.Input) {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *WorkloadDeploymentInput) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given []WorkloadDeploymentBlueprintInputType and assigns it to the Input field.
func (o *WorkloadDeploymentInput) SetInput(v []WorkloadDeploymentBlueprintInputType) {
	o.Input = v
}

// GetObjectGenerationFailed returns the ObjectGenerationFailed field value if set, zero value otherwise.
func (o *WorkloadDeploymentInput) GetObjectGenerationFailed() bool {
	if o == nil || IsNil(o.ObjectGenerationFailed) {
		var ret bool
		return ret
	}
	return *o.ObjectGenerationFailed
}

// GetObjectGenerationFailedOk returns a tuple with the ObjectGenerationFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkloadDeploymentInput) GetObjectGenerationFailedOk() (*bool, bool) {
	if o == nil || IsNil(o.ObjectGenerationFailed) {
		return nil, false
	}
	return o.ObjectGenerationFailed, true
}

// HasObjectGenerationFailed returns a boolean if a field has been set.
func (o *WorkloadDeploymentInput) HasObjectGenerationFailed() bool {
	if o != nil && !IsNil(o.ObjectGenerationFailed) {
		return true
	}

	return false
}

// SetObjectGenerationFailed gets a reference to the given bool and assigns it to the ObjectGenerationFailed field.
func (o *WorkloadDeploymentInput) SetObjectGenerationFailed(v bool) {
	o.ObjectGenerationFailed = &v
}

// GetWorkloadDeployment returns the WorkloadDeployment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkloadDeploymentInput) GetWorkloadDeployment() WorkloadWorkloadDeploymentRelationship {
	if o == nil || IsNil(o.WorkloadDeployment.Get()) {
		var ret WorkloadWorkloadDeploymentRelationship
		return ret
	}
	return *o.WorkloadDeployment.Get()
}

// GetWorkloadDeploymentOk returns a tuple with the WorkloadDeployment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkloadDeploymentInput) GetWorkloadDeploymentOk() (*WorkloadWorkloadDeploymentRelationship, bool) {
	if o == nil {
		return nil, false
	}
	return o.WorkloadDeployment.Get(), o.WorkloadDeployment.IsSet()
}

// HasWorkloadDeployment returns a boolean if a field has been set.
func (o *WorkloadDeploymentInput) HasWorkloadDeployment() bool {
	if o != nil && o.WorkloadDeployment.IsSet() {
		return true
	}

	return false
}

// SetWorkloadDeployment gets a reference to the given NullableWorkloadWorkloadDeploymentRelationship and assigns it to the WorkloadDeployment field.
func (o *WorkloadDeploymentInput) SetWorkloadDeployment(v WorkloadWorkloadDeploymentRelationship) {
	o.WorkloadDeployment.Set(&v)
}

// SetWorkloadDeploymentNil sets the value for WorkloadDeployment to be an explicit nil
func (o *WorkloadDeploymentInput) SetWorkloadDeploymentNil() {
	o.WorkloadDeployment.Set(nil)
}

// UnsetWorkloadDeployment ensures that no value is present for WorkloadDeployment, not even an explicit nil
func (o *WorkloadDeploymentInput) UnsetWorkloadDeployment() {
	o.WorkloadDeployment.Unset()
}

func (o WorkloadDeploymentInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkloadDeploymentInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedMoBaseMo, errMoBaseMo := json.Marshal(o.MoBaseMo)
	if errMoBaseMo != nil {
		return map[string]interface{}{}, errMoBaseMo
	}
	errMoBaseMo = json.Unmarshal([]byte(serializedMoBaseMo), &toSerialize)
	if errMoBaseMo != nil {
		return map[string]interface{}{}, errMoBaseMo
	}
	if _, exists := toSerialize["ClassId"]; !exists {
		toSerialize["ClassId"] = o.GetDefaultClassId()
	}
	toSerialize["ClassId"] = o.ClassId
	if _, exists := toSerialize["ObjectType"]; !exists {
		toSerialize["ObjectType"] = o.GetDefaultObjectType()
	}
	toSerialize["ObjectType"] = o.ObjectType
	if !IsNil(o.GenNumber) {
		toSerialize["GenNumber"] = o.GenNumber
	}
	if o.Input != nil {
		toSerialize["Input"] = o.Input
	}
	if !IsNil(o.ObjectGenerationFailed) {
		toSerialize["ObjectGenerationFailed"] = o.ObjectGenerationFailed
	}
	if o.WorkloadDeployment.IsSet() {
		toSerialize["WorkloadDeployment"] = o.WorkloadDeployment.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkloadDeploymentInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ClassId",
		"ObjectType",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{
		"ClassId":    o.GetDefaultClassId,
		"ObjectType": o.GetDefaultObjectType,
	}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	type WorkloadDeploymentInputWithoutEmbeddedStruct struct {
		// The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
		ClassId string `json:"ClassId"`
		// The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
		ObjectType string `json:"ObjectType"`
		// A sequential number that increments whenever the input changes.
		GenNumber *int64                                 `json:"GenNumber,omitempty"`
		Input     []WorkloadDeploymentBlueprintInputType `json:"Input,omitempty"`
		// The state of the object generation performed using this input. If object generation fails, then this is set to true when the generated objects are restored to their prior state.
		ObjectGenerationFailed *bool                                          `json:"ObjectGenerationFailed,omitempty"`
		WorkloadDeployment     NullableWorkloadWorkloadDeploymentRelationship `json:"WorkloadDeployment,omitempty"`
	}

	varWorkloadDeploymentInputWithoutEmbeddedStruct := WorkloadDeploymentInputWithoutEmbeddedStruct{}

	err = json.Unmarshal(data, &varWorkloadDeploymentInputWithoutEmbeddedStruct)
	if err == nil {
		varWorkloadDeploymentInput := _WorkloadDeploymentInput{}
		varWorkloadDeploymentInput.ClassId = varWorkloadDeploymentInputWithoutEmbeddedStruct.ClassId
		varWorkloadDeploymentInput.ObjectType = varWorkloadDeploymentInputWithoutEmbeddedStruct.ObjectType
		varWorkloadDeploymentInput.GenNumber = varWorkloadDeploymentInputWithoutEmbeddedStruct.GenNumber
		varWorkloadDeploymentInput.Input = varWorkloadDeploymentInputWithoutEmbeddedStruct.Input
		varWorkloadDeploymentInput.ObjectGenerationFailed = varWorkloadDeploymentInputWithoutEmbeddedStruct.ObjectGenerationFailed
		varWorkloadDeploymentInput.WorkloadDeployment = varWorkloadDeploymentInputWithoutEmbeddedStruct.WorkloadDeployment
		*o = WorkloadDeploymentInput(varWorkloadDeploymentInput)
	} else {
		return err
	}

	varWorkloadDeploymentInput := _WorkloadDeploymentInput{}

	err = json.Unmarshal(data, &varWorkloadDeploymentInput)
	if err == nil {
		o.MoBaseMo = varWorkloadDeploymentInput.MoBaseMo
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ClassId")
		delete(additionalProperties, "ObjectType")
		delete(additionalProperties, "GenNumber")
		delete(additionalProperties, "Input")
		delete(additionalProperties, "ObjectGenerationFailed")
		delete(additionalProperties, "WorkloadDeployment")

		// remove fields from embedded structs
		reflectMoBaseMo := reflect.ValueOf(o.MoBaseMo)
		for i := 0; i < reflectMoBaseMo.Type().NumField(); i++ {
			t := reflectMoBaseMo.Type().Field(i)

			if jsonTag := t.Tag.Get("json"); jsonTag != "" {
				fieldName := ""
				if commaIdx := strings.Index(jsonTag, ","); commaIdx > 0 {
					fieldName = jsonTag[:commaIdx]
				} else {
					fieldName = jsonTag
				}
				if fieldName != "AdditionalProperties" {
					delete(additionalProperties, fieldName)
				}
			}
		}

		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkloadDeploymentInput struct {
	value *WorkloadDeploymentInput
	isSet bool
}

func (v NullableWorkloadDeploymentInput) Get() *WorkloadDeploymentInput {
	return v.value
}

func (v *NullableWorkloadDeploymentInput) Set(val *WorkloadDeploymentInput) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkloadDeploymentInput) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkloadDeploymentInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkloadDeploymentInput(val *WorkloadDeploymentInput) *NullableWorkloadDeploymentInput {
	return &NullableWorkloadDeploymentInput{value: val, isSet: true}
}

func (v NullableWorkloadDeploymentInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkloadDeploymentInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
