/*
Cisco Intersight

Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document.

API version: 1.0.11-15830
Contact: intersight@cisco.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intersight

import (
	"encoding/json"
)

// TelemetryDruidExtractionFunctionInlineLookupAllOfLookup struct for TelemetryDruidExtractionFunctionInlineLookupAllOfLookup
type TelemetryDruidExtractionFunctionInlineLookupAllOfLookup struct {
	Type                 *string                `json:"type,omitempty"`
	Map                  map[string]interface{} `json:"map,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TelemetryDruidExtractionFunctionInlineLookupAllOfLookup TelemetryDruidExtractionFunctionInlineLookupAllOfLookup

// NewTelemetryDruidExtractionFunctionInlineLookupAllOfLookup instantiates a new TelemetryDruidExtractionFunctionInlineLookupAllOfLookup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTelemetryDruidExtractionFunctionInlineLookupAllOfLookup() *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup {
	this := TelemetryDruidExtractionFunctionInlineLookupAllOfLookup{}
	return &this
}

// NewTelemetryDruidExtractionFunctionInlineLookupAllOfLookupWithDefaults instantiates a new TelemetryDruidExtractionFunctionInlineLookupAllOfLookup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTelemetryDruidExtractionFunctionInlineLookupAllOfLookupWithDefaults() *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup {
	this := TelemetryDruidExtractionFunctionInlineLookupAllOfLookup{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) SetType(v string) {
	o.Type = &v
}

// GetMap returns the Map field value if set, zero value otherwise.
func (o *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) GetMap() map[string]interface{} {
	if o == nil || o.Map == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Map
}

// GetMapOk returns a tuple with the Map field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) GetMapOk() (map[string]interface{}, bool) {
	if o == nil || o.Map == nil {
		return nil, false
	}
	return o.Map, true
}

// HasMap returns a boolean if a field has been set.
func (o *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) HasMap() bool {
	if o != nil && o.Map != nil {
		return true
	}

	return false
}

// SetMap gets a reference to the given map[string]interface{} and assigns it to the Map field.
func (o *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) SetMap(v map[string]interface{}) {
	o.Map = v
}

func (o TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Map != nil {
		toSerialize["map"] = o.Map
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) UnmarshalJSON(bytes []byte) (err error) {
	varTelemetryDruidExtractionFunctionInlineLookupAllOfLookup := _TelemetryDruidExtractionFunctionInlineLookupAllOfLookup{}

	if err = json.Unmarshal(bytes, &varTelemetryDruidExtractionFunctionInlineLookupAllOfLookup); err == nil {
		*o = TelemetryDruidExtractionFunctionInlineLookupAllOfLookup(varTelemetryDruidExtractionFunctionInlineLookupAllOfLookup)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "map")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup struct {
	value *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup
	isSet bool
}

func (v NullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup) Get() *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup {
	return v.value
}

func (v *NullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup) Set(val *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) {
	v.value = val
	v.isSet = true
}

func (v NullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup) IsSet() bool {
	return v.isSet
}

func (v *NullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup(val *TelemetryDruidExtractionFunctionInlineLookupAllOfLookup) *NullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup {
	return &NullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup{value: val, isSet: true}
}

func (v NullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTelemetryDruidExtractionFunctionInlineLookupAllOfLookup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
